import { JobPost, UserLocation } from '@/types/job';

export function calculateHaversineDistance(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number
): number {
  const R = 6371; // Earth radius in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c * 10) / 10;
}

export const MOCK_JOBS: Omit<JobPost, 'distanceKm'>[] = [
  {
    id: 'job-au-tile-1',
    title: '시드니 스트라스필드 현장 타일공 및 타일 구인 (경력자 & 중간기술자 모집)',
    companyName: '시드니 K-Tile Construction (호주 시드니)',
    companyLogo: '🧱',
    category: 'LOGISTICS',
    categoryName: '물류 & 현장',
    locationName: 'Strathfield Plaza, Strathfield NSW 2135 (호주 시드니 한인타운)',
    latitude: -33.8765,
    longitude: 151.0887,
    salary: '일급 AUD $320 ~ $450 (능력별 우대)',
    employmentType: 'Full-time',
    matchScore: 98,
    skills: ['호주 타일 구인', '시드니 타일공', '방수 작업', '경력 우대'],
    postedAt: '방금 전',
    deadline: '7일 게시 중 (D-7일)',
    description: '시드니 전역 아파트 및 주택 현장 타일공 긴급 구인. 자차 소지자 우대하며 주 5일~6일 현장 출근.',
    isEasyApply: true,
    imageUrl: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&auto=format&fit=crop&q=80',
    isPaid: true,
    isPremiumAd: true,
    adPrice: 30.00,
    paidAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    commuteTimeEstimate: { transitMinutes: 15, carMinutes: 10 },
  },
  {
    id: 'job-au-clean-1',
    title: '시드니 CBD 상업용 오피스 청소 알바 및 야간 클리닝 팀원 구인',
    companyName: 'CleanSydney Pro Services (시드니 중심가)',
    companyLogo: '🧹',
    category: 'LODGING_CLEANING',
    categoryName: '숙박 & 청소',
    locationName: 'George St, Sydney NSW 2000 (시드니 CBD 중심가)',
    latitude: -33.8688,
    longitude: 151.2093,
    salary: '시급 AUD $28 ~ $35 + 주휴 수당',
    employmentType: 'Part-time',
    matchScore: 95,
    skills: ['시드니 청소 알바', '상업용 청소', '워홀 가능', '야간 클리닝'],
    postedAt: '2시간 전',
    deadline: '7일 게시 중 (D-6일)',
    description: '시드니 CBD 오피스 빌딩 야간 상업용 청소 알바 모집. 초보자 교육 제공하며 워킹홀리데이 학생 환영.',
    isEasyApply: true,
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&auto=format&fit=crop&q=80',
    isPaid: true,
    isPremiumAd: true,
    adPrice: 30.00,
    paidAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    commuteTimeEstimate: { transitMinutes: 12, carMinutes: 8 },
  },
  {
    id: 'job-au-acc-1',
    title: '호주 시드니 법인 회계사 채용 (Tax & Accounting Junior/Senior)',
    companyName: 'K-Partners Accounting Firm (호주 회계사)',
    companyLogo: '📊',
    category: 'TECH',
    categoryName: '기술 & IT',
    locationName: 'Pitt St, Sydney NSW 2000 (시드니 금융 지구)',
    latitude: -33.8710,
    longitude: 151.2080,
    salary: '연봉 AUD $75,000 ~ $95,000 + Super',
    employmentType: 'Full-time',
    matchScore: 92,
    skills: ['호주 회계사 채용', 'CPA Australia', 'Xero/MYOB', 'Tax Return'],
    postedAt: '오늘',
    deadline: '7일 게시 중 (D-7일)',
    description: '시드니 CBD 대표 한인 회계법인에서 세무 회계 및 법인 전담 회계사를 모십니다.',
    isEasyApply: true,
    imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format&fit=crop&q=80',
    isPaid: true,
    isPremiumAd: true,
    adPrice: 30.00,
    paidAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    commuteTimeEstimate: { transitMinutes: 10, carMinutes: 10 },
  },
  {
    id: 'job-au-melb-1',
    title: '멜버른 워홀 일자리 - 감성 K-Cafe 바리스타 & 핫플 브런치 직원 모집',
    companyName: 'Melb K-Cafe & Bakery (멜버른 시티)',
    companyLogo: '☕',
    category: 'F_AND_B',
    categoryName: 'F&B (한인식당/카페)',
    locationName: 'Swanston St, Melbourne VIC 3000 (멜버른 멜번 시티)',
    latitude: -37.8136,
    longitude: 144.9631,
    salary: '시급 AUD $27.50 ~ $33 + Tip',
    employmentType: 'Full-time',
    matchScore: 94,
    skills: ['멜버른 워홀 일자리', '바리스타', '브런치 제조', '영어 가능자'],
    postedAt: '3시간 전',
    deadline: '7일 게시 중 (D-6일)',
    description: '멜버른 시티 중심가에 위치한 인기 한인 디저트 카페입니다. 워킹홀리데이 비자 6개월 이상 소지자 대환영.',
    isEasyApply: true,
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop&q=80',
    isPaid: true,
    isPremiumAd: true,
    adPrice: 30.00,
    paidAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    commuteTimeEstimate: { transitMinutes: 8, carMinutes: 6 },
  },
  {
    id: 'job-au-brisbane-1',
    title: '브리스번 한인 구인 및 브리스번 타일공 구직/보조 기술자 긴급 모집',
    companyName: 'Brisbane Tile & Living (브리스번)',
    companyLogo: '🛠️',
    category: 'LOGISTICS',
    categoryName: '물류 & 현장',
    locationName: 'Sunnybank Plaza, QLD 4109 (브리스번 서니뱅크)',
    latitude: -27.5714,
    longitude: 153.0617,
    salary: '일급 AUD $280 ~ $400',
    employmentType: 'Full-time',
    matchScore: 89,
    skills: ['브리스번 타일공 구직', '브리스번 한인 구인', '현장 타일', '차량 지원'],
    postedAt: '1일 전',
    deadline: '7일 게시 중 (D-5일)',
    description: '브리스번 서니뱅크 지역 아파트 타일 현장 보조 및 기량자 긴급 채용.',
    isEasyApply: true,
    isPaid: true,
    paidAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    commuteTimeEstimate: { transitMinutes: 20, carMinutes: 15 },
  },
  {
    id: 'job-nz-auckland-1',
    title: '뉴질랜드 오클랜드 한인 구인구직 - K-BBQ 전문 식당 셰프 & 홀 매니저',
    companyName: '오클랜드 수라 한식당 (뉴질랜드 오클랜드)',
    companyLogo: '🍲',
    category: 'F_AND_B',
    categoryName: 'F&B (한인식당/카페)',
    locationName: 'Queen St, Auckland CBD 1010 (뉴질랜드 오클랜드 시티)',
    latitude: -36.8485,
    longitude: 174.7633,
    salary: '시급 NZD $26 ~ $32 + 주휴 수당',
    employmentType: 'Full-time',
    matchScore: 96,
    skills: ['뉴질랜드 오클랜드 한인 구인구직', '한식 조리', '홀 매니저', '비자 지원'],
    postedAt: '5시간 전',
    deadline: '7일 게시 중 (D-6일)',
    description: '뉴질랜드 오클랜드 시티 메인 스트리트 위치한 한식당에서 메인 조리장 모십니다.',
    isEasyApply: true,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    isPaid: true,
    isPremiumAd: true,
    adPrice: 30.00,
    paidAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    commuteTimeEstimate: { transitMinutes: 10, carMinutes: 8 },
  },
  {
    id: 'job-nz-christ-1',
    title: '뉴질랜드 크라이스트처치 한인 구인 - 부티크 호텔 객실 클리닝 매니저',
    companyName: 'Christchurch Stay Hotel (크라이스트처치)',
    companyLogo: '🏨',
    category: 'LODGING_CLEANING',
    categoryName: '숙박 & 청소',
    locationName: 'Cathedral Square, Christchurch 8011 (뉴질랜드 크라이스트처치)',
    latitude: -43.5321,
    longitude: 172.6362,
    salary: '시급 NZD $25 ~ $30',
    employmentType: 'Full-time',
    matchScore: 91,
    skills: ['뉴질랜드 크라이스트처치 한인 구인', '호텔 청소', '객실 관리', '영주권 가능'],
    postedAt: '오늘',
    deadline: '7일 게시 중 (D-7일)',
    description: '크라이스트처치 중심가 레지던스 호텔 청소 및 현장 매니저 구인.',
    isEasyApply: true,
    isPaid: true,
    paidAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    commuteTimeEstimate: { transitMinutes: 15, carMinutes: 10 },
  },
];
