import { JobPost, UserLocation } from '@/types/job';

export function calculateHaversineDistance(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number
): number {
  const R = 6371; // Earth radius in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c * 10) / 10;
}

export const MOCK_JOBS: Omit<JobPost, 'distanceKm'>[] = [
  {
    id: 'job-au-sydney-1',
    title: '시드니 K-Tile 현장 타일공 및 타일 보조 구인',
    companyName: '시드니 K-Tile Construction (호주 시드니)',
    companyLogo: '🧱',
    category: 'LOGISTICS',
    categoryName: '물류 & 현장',
    locationName: 'Strathfield Plaza, Strathfield NSW 2135 (호주 시드니 한인타운)',
    latitude: -33.8765,
    longitude: 151.0887,
    salary: '일급 AUD $320 ~ $450 (능력별 우대)',
    employmentType: 'Full-time',
    matchScore: 98,
    skills: ['호주 타일 구인', '시드니 타일공', '경력 우대'],
    postedAt: '방금 전',
    deadline: '7일 게시 중 (D-7일)',
    description: '시드니 전역 아파트 현장 타일공 긴급 구인. 자차 소지자 우대하며 주 5일~6일 현장 출근.',
    isEasyApply: true,
    imageUrl: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&auto=format&fit=crop&q=80',
    authorEmail: 'jwmaxum@gmail.com',
    isPaid: true,
    isPremiumAd: true,
    adPrice: 30.00,
    paidAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    commuteTimeEstimate: { transitMinutes: 15, carMinutes: 10 },
  },
  {
    id: 'job-au-melb-1',
    title: '멜버른 워홀 일자리 - 감성 K-Cafe 바리스타 직원 모집',
    companyName: 'Melb K-Cafe & Bakery (멜버른 시티)',
    companyLogo: '☕',
    category: 'F_AND_B',
    categoryName: 'F&B (한인식당/카페)',
    locationName: 'Swanston St, Melbourne VIC 3000 (멜버른 멜번 시티)',
    latitude: -37.8136,
    longitude: 144.9631,
    salary: '시급 AUD $27.50 ~ $33 + Tip',
    employmentType: 'Full-time',
    matchScore: 94,
    skills: ['멜버른 워홀 일자리', '바리스타', '브런치 제조'],
    postedAt: '3시간 전',
    deadline: '7일 게시 중 (D-6일)',
    description: '멜버른 시티 중심가에 위치한 인기 한인 카페입니다. 워킹홀리데이 비자 소지자 대환영.',
    isEasyApply: true,
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop&q=80',
    authorEmail: 'jwmaxum@gmail.com',
    isPaid: true,
    isPremiumAd: true,
    adPrice: 30.00,
    paidAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    commuteTimeEstimate: { transitMinutes: 8, carMinutes: 6 },
  },
  {
    id: 'job-au-goldcoast-1',
    title: '골드코스트 리조트 객실 청소 및 하우스키핑 직원 채용',
    companyName: 'Gold Coast Ocean Resort (골드코스트)',
    companyLogo: '🧹',
    category: 'LODGING_CLEANING',
    categoryName: '숙박 & 청소',
    locationName: 'Surfers Paradise Blvd, Surfers Paradise QLD 4217',
    latitude: -28.0024,
    longitude: 153.4287,
    salary: '시급 AUD $29.00 ~ $35.00',
    employmentType: 'Contract',
    matchScore: 91,
    skills: ['골드코스트 한인 구인', '리조트 청소', '하우스키핑'],
    postedAt: '2일 전',
    deadline: '7일 게시 중 (D-5일)',
    description: '서퍼스 파라다이스 인근 5성급 리조트 객실 청소 관리 직원을 채용합니다. 영주권자 우대 및 워홀 가능.',
    isEasyApply: true,
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&auto=format&fit=crop&q=80',
    authorEmail: 'jwmaxum@gmail.com',
    isPaid: true,
    paidAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    commuteTimeEstimate: { transitMinutes: 20, carMinutes: 10 },
  },
  {
    id: 'job-nz-auckland-1',
    title: '오클랜드 시티 한식 K-BBQ 전문 식당 주방장 구인',
    companyName: '오클랜드 수라 한식당 (오클랜드)',
    companyLogo: '🍲',
    category: 'F_AND_B',
    categoryName: 'F&B (한인식당/카페)',
    locationName: 'Queen St, Auckland CBD 1010 (뉴질랜드 오클랜드 시티)',
    latitude: -36.8485,
    longitude: 174.7633,
    salary: '연봉 NZD $70,000 ~ $85,000 + 보너스',
    employmentType: 'Full-time',
    matchScore: 96,
    skills: ['뉴질랜드 오클랜드 구인', '한식 조리', '주방장'],
    postedAt: '5시간 전',
    deadline: '7일 게시 중 (D-6일)',
    description: '뉴질랜드 오클랜드 시티 메인 스트리트 위치한 한식당에서 메인 조리장 모십니다. 취업 비자 스폰 가능.',
    isEasyApply: true,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    authorEmail: 'jwmaxum@gmail.com',
    isPaid: true,
    isPremiumAd: true,
    adPrice: 30.00,
    paidAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    commuteTimeEstimate: { transitMinutes: 10, carMinutes: 8 },
  },
  {
    id: 'job-nz-christ-1',
    title: '크라이스트처치 호텔 리셉션 데스크 및 청소 매니저',
    companyName: 'Christchurch Stay Hotel (크라이스트처치)',
    companyLogo: '🏨',
    category: 'LODGING_CLEANING',
    categoryName: '숙박 & 청소',
    locationName: 'Cathedral Square, Christchurch 8011 (뉴질랜드 크라이스트처치)',
    latitude: -43.5321,
    longitude: 172.6362,
    salary: '시급 NZD $25 ~ $30',
    employmentType: 'Full-time',
    matchScore: 91,
    skills: ['뉴질랜드 크라이스트처치', '호텔 청소', '객실 관리'],
    postedAt: '오늘',
    deadline: '7일 게시 중 (D-7일)',
    description: '크라이스트처치 중심가 레지던스 호텔 청소 및 현장 매니저 구인. 오전 근무 위주.',
    isEasyApply: true,
    authorEmail: 'jwmaxum@gmail.com',
    isPaid: true,
    paidAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    commuteTimeEstimate: { transitMinutes: 15, carMinutes: 10 },
  },
];
