import { JobPost, UserLocation } from '@/types/job';

export function calculateHaversineDistance(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number
): number {
  const R = 6371; // Earth radius in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c * 10) / 10;
}

export const MOCK_JOBS: Omit<JobPost, 'distanceKm'>[] = [
  {
    id: 'job-fb-1',
    title: 'LA 한인타운 정통 한식 BBQ 조리장 및 주방 매니저',
    companyName: '수라간 K-BBQ (LA Koreatown)',
    companyLogo: '🍲',
    category: 'F_AND_B',
    categoryName: 'F&B (한인식당/카페)',
    locationName: '3832 Wilshire Blvd, Los Angeles, CA 90010 (LA 한인타운 윌셔 Blvd)',
    latitude: 34.0618,
    longitude: -118.3000,
    salary: '시급 $25 ~ $32 + Tip (연 $62,000)',
    employmentType: 'Visa Sponsored',
    visaTypes: ['E-2', 'H-2B', 'J-1', '영주권 스폰'],
    matchScore: 98,
    skills: ['한식 조리', '주방 관리', '식자재 발주', '팀 리더십'],
    postedAt: '2시간 전',
    deadline: '2026-08-30',
    description: '로스앤젤레스 한인타운 중심에 위치한 프리미엄 K-BBQ 식당에서 주방 총괄 조리장 및 매니저를 모십니다. 비자 지원 가능.',
    isEasyApply: true,
    commuteTimeEstimate: { transitMinutes: 10, carMinutes: 8 },
  },
  {
    id: 'job-fb-2',
    title: '글로벌 K-Dessert 한인 베이커리 카페 매니저 & 바리스타',
    companyName: '달콤 K-Cafe & Bakery',
    companyLogo: '☕',
    category: 'F_AND_B',
    categoryName: 'F&B (한인식당/카페)',
    locationName: '3250 Olympic Blvd, Los Angeles, CA 90006 (올림픽 올림픽몰)',
    latitude: 34.0526,
    longitude: -118.3061,
    salary: '시급 $20 ~ $24 + Tip',
    employmentType: 'Full-time',
    visaTypes: ['OPT', 'J-1', 'H-1B', 'E-2'],
    matchScore: 94,
    skills: ['바리스타', '카페 매니지먼트', '디저트 제조', 'Customer Service'],
    postedAt: '4시간 전',
    deadline: '2026-08-28',
    description: '감성적인 인테리어의 한인 타운 핫플 K-카페입니다. 영어/한국어 이중언어 구사자 우대하며 비자 스폰서십 지원합니다.',
    isEasyApply: true,
    commuteTimeEstimate: { transitMinutes: 15, carMinutes: 12 },
  },
  {
    id: 'job-lc-1',
    title: 'LA 한인타운 호스피탈리티 부티크 호텔/숙박 현장 총괄 매니저',
    companyName: 'K-Residence Hotel & Stay',
    companyLogo: '🏨',
    category: 'LODGING_CLEANING',
    categoryName: '숙박 & 청소',
    locationName: '603 S New Hampshire Ave, Los Angeles, CA 90005',
    latitude: 34.0622,
    longitude: -118.2925,
    salary: '연봉 $52,000 ~ $65,000',
    employmentType: 'Full-time',
    visaTypes: ['E-2', 'H-1B', '영주권 스폰'],
    matchScore: 92,
    skills: ['호텔 예약', '객실 관리', '고객 응대', '시설 점검'],
    postedAt: '오늘',
    deadline: '2026-09-05',
    description: '한인타운 인근 객실 50실 규모의 프리미엄 숙박 레지던스입니다. 숙박 현장 총괄 및 예약 운영 담당자 채용.',
    isEasyApply: true,
    commuteTimeEstimate: { transitMinutes: 12, carMinutes: 10 },
  },
  {
    id: 'job-lc-2',
    title: '상업용 빌딩 & 레지던스 전문 클리닝 24시 팀장',
    companyName: 'CleanPro Korea LLC (캘리포니아)',
    companyLogo: '🧹',
    category: 'LODGING_CLEANING',
    categoryName: '숙박 & 청소',
    locationName: '3435 Wilshire Blvd, Los Angeles, CA 90010',
    latitude: 34.0612,
    longitude: -118.2985,
    salary: '시급 $23 ~ $28 (주 40시간 보장)',
    employmentType: 'Full-time',
    visaTypes: ['H-2B', 'E-2', '영주권 지원'],
    matchScore: 90,
    skills: ['청소 관리', '장비 운용', '인원 배치', '품질 검수'],
    postedAt: '1일 전',
    deadline: '2026-09-01',
    description: '캘리포니아 주요 상업용 건물의 딥 클리닝 및 방역을 담당하는 청소 전문업체입니다. 현장 관리자 긴급 구인.',
    isEasyApply: true,
    commuteTimeEstimate: { transitMinutes: 18, carMinutes: 14 },
  },
  {
    id: 'job-tech-1',
    title: '글로벌 풀스택 백엔드 개발자 (NestJS & Supabase)',
    companyName: 'K-Tech Global Systems',
    companyLogo: '🚀',
    category: 'TECH',
    categoryName: '기술 & IT',
    locationName: '서울 성수동 (성수역 3번출구)',
    latitude: 37.5446,
    longitude: 127.0559,
    salary: '연봉 5,500 ~ 7,500만 원',
    employmentType: 'Full-time',
    visaTypes: ['E-7-1', 'F-4', 'F-6'],
    matchScore: 96,
    skills: ['NestJS', 'PostgreSQL', 'TypeScript', 'Docker'],
    postedAt: '1시간 전',
    deadline: '2026-08-31',
    description: '해외 이민자 커뮤니티용 초고속 매칭 플랫폼 백엔드 개발을 담당할 엔지니어를 모집합니다. 비자 지원 가능.',
    isEasyApply: true,
    commuteTimeEstimate: { transitMinutes: 12, carMinutes: 10 },
  },
  {
    id: 'job-logi-1',
    title: '스마트 물류 센터 현장 및 재고 매니저',
    companyName: 'LogiKorea Corp (수원 센터)',
    companyLogo: '📦',
    category: 'LOGISTICS',
    categoryName: '물류 & 현장',
    locationName: '경기 수원 영통구 매영로 12',
    latitude: 37.2596,
    longitude: 127.0464,
    salary: '월급 350만 원',
    employmentType: 'Full-time',
    visaTypes: ['H-1', 'E-9', 'F-4', 'F-6'],
    matchScore: 85,
    skills: ['Logistics', 'Inventory', 'Bilingual'],
    postedAt: '2일 전',
    deadline: '2026-08-20',
    description: '다국어 소통 능력을 갖춘 물류 매니지먼트 팀원 모집.',
    isEasyApply: false,
    commuteTimeEstimate: { transitMinutes: 65, carMinutes: 45 },
  },
];
